# Generated by Django 5.0.6 on 2025-11-08 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_levelstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('source_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.task')),
            ],
        ),
    ]
