# Generated by Django 5.0.6 on 2025-11-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_levelstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='narrative',
            field=models.TextField(blank=True, null=True),
        ),
    ]
